# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
name: 1.0.$(Rev:r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Dev
  jobs:
  - job: Build
    steps:

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
        feedsToUse: 'select'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        versioningScheme: 'byBuildNumber'
        verbosityPack: 'Diagnostic'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet push'
      inputs:              
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '03d48210-1522-48ae-a74a-2cc9bf61d73c'

- stage: Release
  dependsOn: Dev
  jobs:
  - deployment: PublishPublic
    displayName: 'Publish to Nuget.org'
    environment: 'Public Nuget'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet pack'
            inputs:
              command: 'pack'
              packagesToPack: '**/*.csproj'
              versioningScheme: 'byBuildNumber'
              verbosityPack: 'Diagnostic'
          - task: DotNetCoreCLI@2
            displayName: 'dotnet push'
            inputs:
              command: 'push'              
              packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'Nuget.org'