# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Dev
  jobs:
  - job: Build
    steps:

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'

  - deployment: PublishLocal
    environment: Development
    displayName: 'Publish to Artefacts'
    dependsOn: Build
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'pack'
              packagesToPack: '**/*.csproj'
              nobuild: true
              versioningScheme: 'byBuildNumber'
              verbosityPack: 'Diagnostic'

          - task: DotNetCoreCLI@2
            inputs:              
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: '03d48210-1522-48ae-a74a-2cc9bf61d73c'

- stage: Release
  dependsOn: Dev
  jobs:
  - deployment: PublishPublic
    displayName: 'Publish to Nuget.org'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'push'              
              packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'Nuget.org'